//go:build genwallet

// One-shot operator utility: generates a fresh secp256k1 key, writes it to
// .env.live (mode 0600), and prints ONLY the public address to stdout.
// The private key is never printed. Run with:
//
//	go run -tags genwallet ./scripts/genwallet/
//
// Refuses to overwrite an existing .env.live unless OVERWRITE=1 is set.
package main

import (
	"encoding/hex"
	"fmt"
	"os"

	"github.com/ethereum/go-ethereum/crypto"
)

const envPath = ".env.live"

func main() {
	if _, err := os.Stat(envPath); err == nil && os.Getenv("OVERWRITE") != "1" {
		fmt.Fprintf(os.Stderr, "refusing to overwrite existing %s (set OVERWRITE=1 to force)\n", envPath)
		os.Exit(1)
	}

	priv, err := crypto.GenerateKey()
	if err != nil {
		fmt.Fprintln(os.Stderr, "keygen failed:", err)
		os.Exit(1)
	}
	addr := crypto.PubkeyToAddress(priv.PublicKey).Hex()
	privHex := "0x" + hex.EncodeToString(crypto.FromECDSA(priv))

	body := "" +
		"# Generated by scripts/genwallet — keep this file out of git.\n" +
		"# Address: " + addr + "\n" +
		"LIVE_E2E=1\n" +
		"LIVE_E2E_PRIVATE_KEY=" + privHex + "\n" +
		"LIVE_E2E_RPC_URL=https://sepolia.base.org\n" +
		"X402_PAY_TO=" + addr + "\n"

	if err := os.WriteFile(envPath, []byte(body), 0o600); err != nil {
		fmt.Fprintln(os.Stderr, "write failed:", err)
		os.Exit(1)
	}

	fmt.Println("Wallet generated.")
	fmt.Println("  Address:", addr)
	fmt.Println("  Secrets written to:", envPath, "(mode 0600)")
	fmt.Println("  Private key was NOT printed; read it from the file if you need it.")
}
